/**
 * SKY Academy sound effects, synthesized from scratch.
 *
 * Every sound is generated by this code (sine partials, filtered noise and
 * envelopes), so the files belong to SKY Academy: no samples, no licenses, no
 * copyright claims on Instagram, TikTok or YouTube.
 */

export const SFX_SAMPLE_RATE = 48000;

export interface SkySfxDefinition {
	id: string;
	name: string;
	description: string;
	/** Suggested use, shown in the menu. */
	category: "cuenta" | "revelar" | "interfaz" | "trading" | "transicion";
	render: () => Float32Array;
}

type Partial_ = { ratio: number; amp: number; decay: number };

function buffer(seconds: number) {
	return new Float32Array(Math.max(1, Math.round(seconds * SFX_SAMPLE_RATE)));
}

/** Deterministic noise so every build produces identical files. */
function noiseSource(seed = 1) {
	let state = seed >>> 0 || 1;
	return () => {
		state ^= state << 13;
		state ^= state >>> 17;
		state ^= state << 5;
		return ((state >>> 0) / 0xffffffff) * 2 - 1;
	};
}

function addTone(
	out: Float32Array,
	{
		start = 0,
		freq,
		endFreq,
		amp,
		decay,
		attack = 0.002,
		duration,
		partials = [{ ratio: 1, amp: 1, decay: 1 }],
	}: {
		start?: number;
		freq: number;
		endFreq?: number;
		amp: number;
		/** Time constant in seconds. */
		decay: number;
		attack?: number;
		duration?: number;
		partials?: Partial_[];
	},
) {
	const from = Math.round(start * SFX_SAMPLE_RATE);
	const length = Math.round((duration ?? decay * 7) * SFX_SAMPLE_RATE);
	const phases = partials.map(() => 0);
	for (let i = 0; i < length && from + i < out.length; i++) {
		const t = i / SFX_SAMPLE_RATE;
		const progress = i / length;
		const f = endFreq ? freq * (endFreq / freq) ** progress : freq;
		// soft release over the last 15% so long partials never stop abruptly
		const env = Math.min(1, t / attack, (length - i) / (length * 0.15));
		let sample = 0;
		partials.forEach((partial, index) => {
			phases[index] += (2 * Math.PI * f * partial.ratio) / SFX_SAMPLE_RATE;
			sample +=
				Math.sin(phases[index] ?? 0) * partial.amp * Math.exp(-t / (decay * partial.decay));
		});
		out[from + i] += sample * env * amp;
	}
}

function addNoise(
	out: Float32Array,
	{
		start = 0,
		duration,
		amp,
		envelope,
		lowpass = 1,
		highpass = 0,
		seed = 7,
	}: {
		start?: number;
		duration: number;
		amp: number;
		/** 0..1 progress → gain. */
		envelope: (progress: number) => number;
		/** One-pole low-pass coefficient (1 = open), may vary over progress. */
		lowpass?: number | ((progress: number) => number);
		/** Simple high-pass amount 0..1. */
		highpass?: number;
		seed?: number;
	},
) {
	const random = noiseSource(seed);
	const from = Math.round(start * SFX_SAMPLE_RATE);
	const length = Math.round(duration * SFX_SAMPLE_RATE);
	let low = 0;
	let previous = 0;
	for (let i = 0; i < length && from + i < out.length; i++) {
		const progress = i / length;
		const coefficient = typeof lowpass === "function" ? lowpass(progress) : lowpass;
		low += (random() - low) * coefficient;
		const high = low - previous * highpass;
		previous = low;
		out[from + i] += high * envelope(progress) * amp;
	}
}

/** Scales to a -2 dBFS peak with 3 ms fades so nothing clicks. */
export function finishSfx(samples: Float32Array, peak = 0.79): Float32Array {
	let max = 0;
	for (const value of samples) max = Math.max(max, Math.abs(value));
	const gain = max > 0 ? peak / max : 1;
	const fade = Math.round(0.003 * SFX_SAMPLE_RATE);
	for (let i = 0; i < samples.length; i++) {
		const edge = Math.min(1, i / fade, (samples.length - 1 - i) / fade);
		samples[i] = (samples[i] ?? 0) * gain * Math.max(0, edge);
	}
	return samples;
}

const BELL: Partial_[] = [
	{ ratio: 1, amp: 1, decay: 1 },
	{ ratio: 2.0, amp: 0.55, decay: 0.7 },
	{ ratio: 2.76, amp: 0.4, decay: 0.55 },
	{ ratio: 5.4, amp: 0.25, decay: 0.35 },
	{ ratio: 8.93, amp: 0.12, decay: 0.2 },
];

const CHIME: Partial_[] = [
	{ ratio: 1, amp: 1, decay: 1 },
	{ ratio: 2, amp: 0.3, decay: 0.6 },
	{ ratio: 3, amp: 0.12, decay: 0.4 },
];

export const SKY_SFX: SkySfxDefinition[] = [
	{
		id: "tic",
		name: "Tic",
		description: "Un segundo de la cuenta regresiva",
		category: "cuenta",
		render: () => {
			const out = buffer(0.12);
			addTone(out, { freq: 1900, amp: 0.8, decay: 0.012, duration: 0.1 });
			addTone(out, { freq: 3800, amp: 0.25, decay: 0.006, duration: 0.05 });
			addNoise(out, { duration: 0.01, amp: 0.4, envelope: (p) => 1 - p, highpass: 0.9 });
			return finishSfx(out, 0.6);
		},
	},
	{
		id: "tac",
		name: "Tac",
		description: "Segundo alterno (tic-tac)",
		category: "cuenta",
		render: () => {
			const out = buffer(0.12);
			addTone(out, { freq: 1250, amp: 0.8, decay: 0.014, duration: 0.1 });
			addNoise(out, { duration: 0.01, amp: 0.35, envelope: (p) => 1 - p, highpass: 0.9 });
			return finishSfx(out, 0.6);
		},
	},
	{
		id: "tic-tac-3",
		name: "Tic-tac 3 s",
		description: "Tres segundos de reloj seguidos",
		category: "cuenta",
		render: () => {
			const out = buffer(3);
			for (let i = 0; i < 6; i++) {
				const start = i * 0.5;
				addTone(out, {
					start,
					freq: i % 2 === 0 ? 1900 : 1250,
					amp: 0.8,
					decay: 0.013,
					duration: 0.1,
				});
				addNoise(out, {
					start,
					duration: 0.01,
					amp: 0.35,
					envelope: (p) => 1 - p,
					highpass: 0.9,
					seed: 11 + i,
				});
			}
			return finishSfx(out, 0.6);
		},
	},
	{
		id: "ding",
		name: "Ding (revelar)",
		description: "Al terminar la cuenta o mostrar la respuesta",
		category: "revelar",
		render: () => {
			const out = buffer(1.6);
			addTone(out, { freq: 1318.5, amp: 0.8, decay: 0.35, partials: BELL, duration: 1.6 });
			return finishSfx(out);
		},
	},
	{
		id: "subida",
		name: "Subida (suspenso)",
		description: "Sube la tensión antes de revelar",
		category: "revelar",
		render: () => {
			const out = buffer(1.8);
			addTone(out, {
				freq: 180,
				endFreq: 1400,
				amp: 0.35,
				decay: 100,
				attack: 1.5,
				duration: 1.8,
				partials: [
					{ ratio: 1, amp: 1, decay: 1 },
					{ ratio: 1.5, amp: 0.4, decay: 1 },
				],
			});
			addNoise(out, {
				duration: 1.8,
				amp: 0.5,
				envelope: (p) => p ** 2,
				lowpass: (p) => 0.05 + p * 0.5,
			});
			return finishSfx(out, 0.7);
		},
	},
	{
		id: "redoble",
		name: "Redoble",
		description: "Tambor antes del resultado",
		category: "revelar",
		render: () => {
			const out = buffer(2.6);
			let t = 0;
			let hit = 0;
			while (t < 1.8) {
				addNoise(out, {
					start: t,
					duration: 0.05,
					amp: 0.3 + (t / 1.8) * 0.6,
					envelope: (p) => (1 - p) ** 2,
					lowpass: 0.3,
					seed: 100 + hit,
				});
				addTone(out, { start: t, freq: 190, amp: 0.25, decay: 0.03, duration: 0.05 });
				t += 0.055 - (t / 1.8) * 0.02;
				hit++;
			}
			addTone(out, { start: 1.85, freq: 70, amp: 1, decay: 0.2, duration: 0.7 });
			addNoise(out, {
				start: 1.85,
				duration: 0.75,
				amp: 0.8,
				envelope: (p) => (1 - p) ** 3,
				lowpass: 0.8,
				seed: 999,
			});
			return finishSfx(out);
		},
	},
	{
		id: "pop",
		name: "Pop",
		description: "Aparece un texto, sticker o botón",
		category: "interfaz",
		render: () => {
			const out = buffer(0.18);
			addTone(out, { freq: 380, endFreq: 1100, amp: 1, decay: 0.03, duration: 0.15 });
			return finishSfx(out, 0.7);
		},
	},
	{
		id: "click",
		name: "Clic",
		description: "Clic del mouse (botón seguir, me gusta)",
		category: "interfaz",
		render: () => {
			const out = buffer(0.08);
			addNoise(out, { duration: 0.012, amp: 1, envelope: (p) => 1 - p, highpass: 0.95 });
			addTone(out, { freq: 3200, amp: 0.4, decay: 0.004, duration: 0.03 });
			addNoise(out, {
				start: 0.035,
				duration: 0.008,
				amp: 0.5,
				envelope: (p) => 1 - p,
				highpass: 0.95,
				seed: 3,
			});
			return finishSfx(out, 0.6);
		},
	},
	{
		id: "campanita",
		name: "Campanita",
		description: "Activar notificaciones",
		category: "interfaz",
		render: () => {
			const out = buffer(1.4);
			addTone(out, { freq: 2093, amp: 0.7, decay: 0.25, partials: BELL, duration: 1.2 });
			addTone(out, {
				start: 0.16,
				freq: 2637,
				amp: 0.6,
				decay: 0.3,
				partials: BELL,
				duration: 1.2,
			});
			return finishSfx(out, 0.7);
		},
	},
	{
		id: "whoosh",
		name: "Whoosh",
		description: "Transición o entrada rápida",
		category: "transicion",
		render: () => {
			const out = buffer(0.7);
			addNoise(out, {
				duration: 0.7,
				amp: 1,
				envelope: (p) => Math.sin(Math.PI * p) ** 2,
				lowpass: (p) => 0.04 + Math.sin(Math.PI * p) * 0.35,
			});
			return finishSfx(out, 0.7);
		},
	},
	{
		id: "impacto",
		name: "Impacto",
		description: "Golpe grave para un dato fuerte",
		category: "transicion",
		render: () => {
			const out = buffer(1.2);
			addTone(out, { freq: 90, endFreq: 42, amp: 1, decay: 0.25, duration: 1.2 });
			addNoise(out, {
				duration: 0.3,
				amp: 0.5,
				envelope: (p) => (1 - p) ** 4,
				lowpass: 0.3,
			});
			return finishSfx(out);
		},
	},
	{
		id: "exito",
		name: "Éxito (TP)",
		description: "Take profit, operación ganadora",
		category: "trading",
		render: () => {
			const out = buffer(1.4);
			[523.25, 659.25, 783.99, 1046.5].forEach((freq, index) => {
				addTone(out, {
					start: index * 0.09,
					freq,
					amp: 0.55,
					decay: 0.25,
					partials: CHIME,
					duration: 1,
				});
			});
			return finishSfx(out, 0.7);
		},
	},
	{
		id: "error",
		name: "Error (SL)",
		description: "Stop loss o entrada incorrecta",
		category: "trading",
		render: () => {
			const out = buffer(0.7);
			for (const [start, freq] of [
				[0, 233],
				[0.22, 185],
			] as const) {
				addTone(out, {
					start,
					freq,
					amp: 0.6,
					decay: 0.3,
					duration: 0.2,
					partials: [
						{ ratio: 1, amp: 1, decay: 1 },
						{ ratio: 3, amp: 0.33, decay: 1 },
						{ ratio: 5, amp: 0.2, decay: 1 },
					],
				});
			}
			return finishSfx(out, 0.6);
		},
	},
	{
		id: "caja",
		name: "Ka-ching (ganancia)",
		description: "Dinero, ganancia, resultado",
		category: "trading",
		render: () => {
			const out = buffer(1.3);
			addNoise(out, { duration: 0.05, amp: 0.7, envelope: (p) => 1 - p, highpass: 0.8 });
			addTone(out, { start: 0.06, freq: 2349, amp: 0.6, decay: 0.3, partials: BELL });
			addTone(out, { start: 0.1, freq: 3136, amp: 0.5, decay: 0.35, partials: BELL });
			return finishSfx(out, 0.7);
		},
	},
];

/** 16-bit PCM mono WAV. */
export function encodeWav(samples: Float32Array, sampleRate = SFX_SAMPLE_RATE): Buffer {
	const data = Buffer.alloc(samples.length * 2);
	for (let i = 0; i < samples.length; i++) {
		const value = Math.max(-1, Math.min(1, samples[i] ?? 0));
		data.writeInt16LE(Math.round(value * 32767), i * 2);
	}
	const header = Buffer.alloc(44);
	header.write("RIFF", 0);
	header.writeUInt32LE(36 + data.length, 4);
	header.write("WAVE", 8);
	header.write("fmt ", 12);
	header.writeUInt32LE(16, 16);
	header.writeUInt16LE(1, 20);
	header.writeUInt16LE(1, 22);
	header.writeUInt32LE(sampleRate, 24);
	header.writeUInt32LE(sampleRate * 2, 28);
	header.writeUInt16LE(2, 32);
	header.writeUInt16LE(16, 34);
	header.write("data", 36);
	header.writeUInt32LE(data.length, 40);
	return Buffer.concat([header, data]);
}
